### ISSUE TITLE
can't play the stream

### ISSUE THREAD

**Issue by tatuan25** [nopbreak/TwitchMod#35]
![Screenshot_20210114-023121](https://user-images.githubusercontent.com/77410779/104500210-b325da80-5610-11eb-85e8-3577c098f7c0.png)
"the stream is over" it said... i have checked every channels, still the same, the chat still working find tho. can u check this out please, thanks

**Comment by nopbreak** [comment]
If you have problems with watching streams, turn off SureStream Adblock and restart app.

**Comment by Wesleycandido** [comment]
Yea its over

Em qua, 13 de jan de 2021 16:34, tatuan25 <notifications@github.com>
escreveu:

**Comment by tatuan25** [comment]
> If you have problems with watching streams, turn off SureStream Adblock and restart app.

 it works normal now. thanks man

**Comment by tatuan25** [comment]
> If you have problems with watching streams, turn off SureStream Adblock and restart app.

hey man, the same problem is back again, can't watch the stream even tho it's still live. i have turned off both non-stream adblock & surestream adblock, and restarted the app, still can't watch... can u check it out, thanks

**Comment by tatuan25** [comment]
oh wait, i think this is my own internet problem. sorry man xD

**Comment by preynolds2** [comment]
It's not just your internet.  I couldn't play stream either.

**Comment by TRUEtennisfan** [comment]
Having the same issue :(

**Comment by AlexWayfer** [comment]
Update the client or disable ads block: https://t.me/pubTw/69

**Comment by 5c0tt-b0t** [comment]
@nopbreak - **thank you so much for this amazing app! it is really appreciated!!** 

### Issue:
Turning off the ad-blocker no longer works.
I even tried clearing cache and data, logging in again and turning off the ad-blocker only (no other mods) and still no streams play.
I even tried uninstalling and re-installing, again only turned off the ad-blocker (no other mods), still no streams play.

### Request:
If there is a newer build on Telegram to try, then why not just link it underneath the current URL in the ReadMe? or make it another branch on Github? e.g "unstable" or "beta" etc? I do not have Telegram and will not download another app and register my phone number just to get one APK every week or so (I'm sure I'm not the only one!), whilst Telegram makes a good forum, it shouldnt be the only place to get the latest build, forcing us to use Telegram or use an older build, when we are already using Github, that has bug-tracking, issues, pages etc etc...
So please consider adding latest builds here on Github too, thank you.

**Comment by nopbreak** [comment]
@5c0tt-b0t 
I updated the files for the latest patch. Streams should be working now.

**Comment by 5c0tt-b0t** [comment]
just fresh installed official lineage os 17.1 (OnePlus 5T), after login (no mods) the same problem still persists, no video & no chat:
![Screenshot_20210125-215901_TwitchMod](https://user-images.githubusercontent.com/63571864/105772424-09244780-5f5a-11eb-969e-64025a9e779b.png)
I remembered you said about turning off the adblock option, afterwards chat now works but video doesnt work still:
![Screenshot_20210125-215709_TwitchMod](https://user-images.githubusercontent.com/63571864/105772575-4ab4f280-5f5a-11eb-9bc3-4e3486aa2908.png)
